kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/seongenie/book-search-web.git
  - git checkout $DRONE_COMMIT

- name: build
  image: node
  commands:
  - npm install
  - npm run test
